services:
  db:
    image: mysql:9.0.1
    env_file:
      - ./.env
    container_name: area-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      area:
        ipv4_address: ${DB_HOST}
    volumes:
      - "./data/db/:/var/lib/mysql"

  back:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-prod
    restart: "always"
    depends_on:
      - decrypt
    volumes:
      - env:/env/
    networks:
      area:
        ipv4_address: ${BACK_HOST}

networks:
  area:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
        - gateway: 172.21.0.1