FROM ubuntu:22.04

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y python3 python3-pip entr

COPY ./requirements.txt /opt/requirements.txt

RUN pip3 install -r /opt/requirements.txt

WORKDIR /app/