FROM ubuntu:22.04

SHELL ["/bin/bash", "-c"]

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y python3 python3-pip python3-mysqldb python3-venv

WORKDIR /env/

RUN python3 -m venv /env/.venv/
RUN source /env/.venv/bin/activate

COPY ./requirements.txt /env/requirements.txt

RUN pip3 install -r /env/requirements.txt

WORKDIR /app/

COPY ./app/ /app/app/

CMD [ "flask", "run", "--no-debug" ]