FROM python:3.9.20-alpine

WORKDIR /app/

COPY ./requirements.txt /app/requirements.txt

RUN pip3 install -r /app/requirements.txt

COPY ./app.py /app/app.py
COPY ./app/ /app/app/

COPY ./env/.env /app/.env

CMD [ "python3", "/app/app.py" ]