FROM ubuntu:22.04

SHELL ["/bin/bash", "-c"]

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y python3 python3-pip python3-mysqldb python3-venv

WORKDIR /env/

COPY ./requirements.txt /env/requirements.txt

RUN python3 -m venv /env/.venv/
RUN source /env/.venv/bin/activate

RUN pip3 install -r /env/requirements.txt

WORKDIR /app/

CMD [ "python3", "/app/app/" ]